### ISSUE TITLE
this error

### ISSUE THREAD

**Issue by imrajatsingla** [redianmarku/ig-dmbot-acc#2]
C:\Users\samsa\OneDrive\Desktop\ig-dmbot-acc>python run.py
Traceback (most recent call last):
  File "C:\Users\samsa\OneDrive\Desktop\ig-dmbot-acc\run.py", line 12, in <module>
    messages = [line.strip() for line in f]
  File "C:\Users\samsa\OneDrive\Desktop\ig-dmbot-acc\run.py", line 12, in <listcomp>
    messages = [line.strip() for line in f]
  File "C:\Users\samsa\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 9: character maps to <undefined>

**Comment by redianmarku** [comment]
did you put the messages list

**Comment by 93Faisal** [comment]
#6  
![error](https://user-images.githubusercontent.com/93975284/141468883-2bf2c9f5-f1c8-40bd-bd58-5493010a49dc.PNG)
Facing this issue at the end of the command "python run.py"    I put my user name and also enter those persons to whom I want to send messages but IG is not opening. Looking to your response in this matter. Thank a lot
